### ISSUE TITLE
Installation + guide

### ISSUE THREAD

**Issue by mikssssss** [Anyrainel/NRBot#3]
Hello,

I'm very new to Github and python here. I'm trying to install this NRBot and following the instructions, but im stuck on step 5

"Copy settings.default.jsonc to settings.jsonc and update config. Refer to comments for instructions."

i can't seem to find the settings.jsonc that the guide is talking about? Can someone help me out? Including on how to run the script itself as i'm very new to this.

Thank you.

**Comment by Systemac** [comment]
You need to rename settings.default.jsonc to settings.jsonc, and refer to comments for instructions.

**Comment by mikssssss** [comment]
Hi Systemac,

Thanks for the tip above. i wonder if it's possible to go through all the setup and test run it with you through discord? To make sure i don't miss anything important to run this scripts :)

**Comment by Systemac** [comment]
Frankly, I haven't found a script this well documented in a long time....
If you ever need to test, I invite you to run the script directly from airtestide, it will allow you to adjust what you want, and no, no discord sorry.
